name: doc_scanner
description: Smart Doc Scanner Pro - Advanced document, card, and image to PDF scanner.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  image_picker: ^1.1.2
  image_picker_android: ^0.8.13+17
  image_picker_platform_interface: ^2.11.1
  permission_handler: ^11.4.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  image: ^4.5.4
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.2
  cunning_document_scanner: ^1.2.3
  printing: ^5.14.3
  syncfusion_flutter_pdf: ^33.2.13
  file_picker: ^11.0.2
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tools/
    - assets/images/
    - assets/images/pdf_tools_banner.png
    - assets/icons/tools/tool_merge_pdf.png
    - assets/icons/tools/tool_split_pdf.png
    - assets/icons/tools/tool_reorder_pages.png
    - assets/icons/tools/tool_compress_pdf.png
    - assets/icons/tools/tool_convert_pdf.png
    - assets/icons/tools/tool_pdf_to_image.png
    - assets/icons/tools/tool_rotate_pdf.png
    - assets/icons/tools/tool_delete_pages.png
    - assets/icons/tools/tool_watermark.png
    - assets/icons/tools/tool_lock_pdf.png
    - assets/icons/tools/tool_unlock_pdf.png
    - assets/icons/tools/tool_redact_pdf.png
